### ISSUE TITLE
Game softlocks on Dolphin when Frankly tries to remove fence

### ISSUE THREAD

**Issue by Glubbins** [Reeds-github/Hero-Mode#2]
Every time Frankly goes to remove the fence after leaving his house, the game will softlock when the fence would normally fall off of the screen. The scene never plays but the game still runs and NPCs move around normally.
![fence](https://user-images.githubusercontent.com/74071426/98404847-e9534680-2030-11eb-8014-75ceeb9af47c.png)

**Comment by Reeds-github** [comment]
I'm pretty sure that's an Dolphin issue, try bringing it up with people like Zephiles
#3457 on Discord
