### ISSUE TITLE
Can't use Plane Mode freely [2.0]

### ISSUE THREAD

**Issue by Kishin667** [Reeds-github/Hero-Mode#3]
I'm on version 2.0 of the demo on Dolphin, I can only choose to go left or right, upon opening the save. If I choose left, both inputs send me flying left.

**Comment by Kishin667** [comment]
So sorry, it was my emulator bugging out. Not an actual issue with the mod!

**Comment by Reeds-github** [comment]
Are you using the recommended version of Dolphin the Github states?

**Comment by Lightkers** [comment]
For me i use 5.O dolphin version and i have this problem and i have 2.0 version of hero mode
